add_test( [==[Color defaults to opaque black]==] /home/kate/src/repos/FPGA-accelerated-triangle-optimizer/tests/triopt_tests [==[--test-case=Color defaults to opaque black]==])
set_tests_properties( [==[Color defaults to opaque black]==] PROPERTIES WORKING_DIRECTORY /home/kate/src/repos/FPGA-accelerated-triangle-optimizer/tests LABELS)
add_test( [==[ImageData stores x_size * y_size pixels]==] /home/kate/src/repos/FPGA-accelerated-triangle-optimizer/tests/triopt_tests [==[--test-case=ImageData stores x_size * y_size pixels]==])
set_tests_properties( [==[ImageData stores x_size * y_size pixels]==] PROPERTIES WORKING_DIRECTORY /home/kate/src/repos/FPGA-accelerated-triangle-optimizer/tests LABELS)
add_test( [==[LoadImageDataFromPNG loads a known PNG]==] /home/kate/src/repos/FPGA-accelerated-triangle-optimizer/tests/triopt_tests [==[--test-case=LoadImageDataFromPNG loads a known PNG]==])
set_tests_properties( [==[LoadImageDataFromPNG loads a known PNG]==] PROPERTIES WORKING_DIRECTORY /home/kate/src/repos/FPGA-accelerated-triangle-optimizer/tests LABELS)
add_test( [==[LoadImageDataFromPNG failes when loading non existant PNG]==] /home/kate/src/repos/FPGA-accelerated-triangle-optimizer/tests/triopt_tests [==[--test-case=LoadImageDataFromPNG failes when loading non existant PNG]==])
set_tests_properties( [==[LoadImageDataFromPNG failes when loading non existant PNG]==] PROPERTIES WORKING_DIRECTORY /home/kate/src/repos/FPGA-accelerated-triangle-optimizer/tests LABELS)
add_test( [==[SaveImageDataToPNG round-trips]==] /home/kate/src/repos/FPGA-accelerated-triangle-optimizer/tests/triopt_tests [==[--test-case=SaveImageDataToPNG round-trips]==])
set_tests_properties( [==[SaveImageDataToPNG round-trips]==] PROPERTIES WORKING_DIRECTORY /home/kate/src/repos/FPGA-accelerated-triangle-optimizer/tests LABELS)
set( triopt_tests_TESTS [==[Color defaults to opaque black]==] [==[ImageData stores x_size * y_size pixels]==] [==[LoadImageDataFromPNG loads a known PNG]==] [==[LoadImageDataFromPNG failes when loading non existant PNG]==] [==[SaveImageDataToPNG round-trips]==])
